### ISSUE TITLE
css居中问题

### ISSUE THREAD

**Issue by zhn4** [zhn4/lotuszhn.github.io#11]
子元素于父元素完全居中
- 方法1，传统margin方法整位置
demo:http://jsbin.com/panatobuma/edit?html,css,output
![image](https://cloud.githubusercontent.com/assets/11404946/21562363/60e68afa-ceb3-11e6-97e4-acb03939e87b.png)
```css
.aaaa {
  border: 1px solid black;
  position: relative;
  width: 300px;
  height: 300px;
}

.bbbb {
  border: 1px solid red;
  position: absolute;
  width: 200px;
  height: 200px;
  top: 50%;
  left: 50%;
  margin-top: -100px;
  margin-left: -100px;
}
```
- 方法2，传统方法相似，使用transform代替margin方法
deom:http://jsbin.com/jovokidiri/edit?html,css,output
![image](https://cloud.githubusercontent.com/assets/11404946/21562920/a453ba66-ceb7-11e6-8015-7c1ab6dea288.png)
```css
.aaaa {
  border: 1px solid black;
  position: relative;
  width: 300px;
  height: 300px;
}

.bbbb {
  border: 1px solid red;
  position: absolute;
  width: 200px;
  height: 200px;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```
- 方法3，top、right、bottom、left都设置为0，margin设置auto自适应
demo:http://jsbin.com/sevaxijede/edit?html,css,output
![image](https://cloud.githubusercontent.com/assets/11404946/21563045/a7203908-ceb8-11e6-8364-1ab27108e695.png)
```css
.aaaa {
  border: 1px solid black;
  position: relative;
  width: 300px;
  height: 300px;
}

.bbbb {
  border: 1px solid red;
  position: absolute;
  width: 200px;
  height: 200px;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  margin: auto;
}
```
- 方法4，flex方法
demo:http://jsbin.com/nuvipiqevu/edit?html,css,output
![image](https://cloud.githubusercontent.com/assets/11404946/21563122/7c4ac710-ceb9-11e6-9eb2-902dac1b3d90.png)
```css
.aaaa {
  border: 1px solid black;
  position: relative;
  width: 300px;
  height: 300px;
  display: flex;
  justify-content: center;
  align-items: center;
}

.bbbb {
  border: 1px solid red;
}
```

文本水平、垂直居中
demo:http://jsbin.com/hizinupibo/edit?html,css,output
![image](https://cloud.githubusercontent.com/assets/11404946/21562734/2d3c14a6-ceb6-11e6-8010-b92d00f77ec4.png)
```css
.aaaa {
  border: 1px solid black;
  height: 200px;
  line-height: 200px;
}

.bbbb {
  border: 1px solid red;
  padding: 20px 0;
}

.cccc {
  border: 1px solid green;
  text-align: center;
}

.dddd {
  border: 1px solid tomato;
}

.dddd div {
  border: 1px solid blue;
  margin: 0 auto;
  width: 50px;
}
```

已知父元素长度和宽度，一个尺寸不确定的图片完全居中
demo:http://jsbin.com/tuqixibogo/edit?html,css,output
```html
  <div class="box">
    <img src="https://tvax1.sinaimg.cn/crop.0.25.1242.1242.180/610cb1e0ly8fmaz2f7nmmj20yi0zx40z.jpg" alt="">
  </div>
```

```css
.box {
  width: 300px;
  height: 300px;
  border: 1px solid red;
  position: relative;
}

img {
  display: block;
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  margin: auto;
  
}
```
