### ISSUE TITLE
纯cssloading效果

### ISSUE THREAD

**Issue by zhn4** [zhn4/lotuszhn.github.io#3]
#### 纯cssloading效果
````css
@keyframes loading {
  0% {
    transform:rotate(0deg);
  }
	100% {
    transform:rotate(360deg);
  }
}

.loading {
  width: 30px;
  height: 30px;
  display: block;
  border-top: 10px solid red;
  border-right: 10px solid yellow;
  border-bottom: 10px solid blue;
  border-left: 10px solid green;
  border-radius: 50px;
  position: fixed;
  top: 50%;
  left: 50%;
  margin-top: -15px;
  margin-left: -15px;
  transform: rotate(360deg);
  animation: loading 2s infinite linear;
}
````
