### ISSUE TITLE
flex-direction: row-reverse;使用

### ISSUE THREAD

**Issue by zhn4** [zhn4/lotuszhn.github.io#4]
#### flex-direction: row-reverse;使用
功能列表：
![function-list](https://github.com/zhn4/demo/blob/master/images/20160502194818.png?raw=true)
左icon，右描述，部分设计需要需要左右反转，效果如上图所示
````html
<div class="show">
  <div class="box">
    <div class="left"></div>
    <div class="right">123</div>
  </div>
      <div class="box">
    <div class="left"></div>
    <div class="right">123</div>
  </div>
      <div class="box">
    <div class="left"></div>
    <div class="right">123</div>
  </div>
      <div class="box">
    <div class="left"></div>
    <div class="right">123</div>
  </div>
      <div class="box">
    <div class="left"></div>
    <div class="right">123</div>
  </div>
      <div class="box">
    <div class="left"></div>
    <div class="right">123</div>
  </div>
</div>
````

````css
.left {
  width: 50px;
  height: 50px;
  background-color: red;
  display: inline-block;
}
.right {
  display: inline-block;
}
.box {
  width: 100px;
  display: flex;
}
.box:nth-child(2n+2) {
  flex-direction: row-reverse;
}
````
